<article class="articleSide">
  <header>
    <h2><?= $article['titre'] ?></h2>
    <p><time><?= $article['date_publication']?></time></p>
    <h3><?= $article['sous_titre'] ?></h3>
  </header>
  <section>
    <?= $article['corps'] ?>
  </section>
      <footer>
        <p><time><?= $article['date_creation']?></time></p>
      </footer>
      <?php foreach($article as $c) {
              $selected = ($c['titre'] == $model['titre']) ? "selected" : "";
              echo "<option value='" . $c['titre'] . "' $selected >" . $c['titre'] . "</option>";
            } ?>
</article>

  <form action="/subscribe" method="post">
  <fieldset>
  <legend>GET MY LATEST UPDATE!</legend>
  <input type="name" name="text" placeholder="first name">
  <input type="email" name="email" placeholder="e.g anna@smith.com">
  <button>Subscribe</button>
  </fieldset>
  </form>
