<!DOCTYPE html>
<html lang="fr"
<head>
  <title>Mischelle PEJO</title>
  <meta charset="utf-8">
  <script src="path/to/jquery.mapael.min.js"></script>
	<link rel="stylesheet" href="public/main.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
</head>
<body class="homepage">
  <header class="welcome">
    <nav>
        <a href="#">About</a>
        <a href="#">Travel Tips</a>
        <a href="#">Destinations</a>
    </nav>
  </header>
  <main class="main-content">
    <?php include "../templates/$template.phtml" ?>
  </main>
  <footer class="footer-content">
    <nav>
        <a href="">About</a>
        <a href="">Profile</a>
        <a href="">Copyright</a>
        <a href="">Privacy Policy</a>
        <a href="">Contact</a>
    </nav>
    <h3>Follow me on the web!</h3>
    <ul>
      <li><a href=""><i class="fab fa-facebook-square"></i></a></li>
      <li><a href=""><i class="fab fa-instagram"></i></a></li>
      <li><a href=""><i class="fab fa-twitter-square"></i></a></li>
    </ul>
  </footer>
</body>
</html>
