
<h1>BLOG</h1>
<fieldset>
  <form action="adduser.php" method="post">
      <div class="container">
        <label for="nom"><b>Family Name</b></label>
        <input type="text" placeholder="Family Name" name="nom" required>

        <label for="prenom"><b>First Name</b></label>
        <input type="text" placeholder="First Name" name="prenom" required>

        <label for="pseudo"><b>NickName</b></label>
        <input type="text" placeholder="NickName" name="pseudo" required>

        <label for="email"><b>E-mail</b></label>
        <input type="text" placeholder="Enter Email" name="uname" required>

        <label for="psw"><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="psw" required>

        <button type="submit">Register</button>
        <label>
          <input type="checkbox" checked="checked" name="remember"> Remember me
        </label>
      </div>
 </form>
</fieldset>
      <div class="container" style="background-color:none>
        <button type="button" class="cancelbtn">Cancel</button>
        <span class="psw">Forgot <a href="#">password?</a></span>
      </div>
